name: Android Feature

on:
    push:
        branches:
            - '*'
            - 'feature/*'
            - '!main'

jobs:

    build:
        name: Compile
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v1
            -   name: set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   name: Compile
                run: bash ./gradlew compileDebugSources compileDebugUnitTestSources -PdisablePreDex --quiet
            -   name: Lint
                run: bash ./gradlew app:lintDebug ktlintCheck -PdisablePreDex --quiet
            -   name: Unit tests
                run: bash ./gradlew test --stacktrace
